spring.application.name=auth-service
server.port=9096

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_auth?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=esta_es_mi_compleja_clave_secreta_foodtruck_2026

logging.file.name=logs/auth-service.log
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{36}] %msg%n
logging.pattern.file=%d{HH:mm:ss} %-5level [%logger{36}] %msg%n
logging.level.root=INFO
logging.level.com.foodtruck.auth_service=INFO

springdoc.swagger-ui.path=/doc/swagger-ui.html
